// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Re.Admin.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Re.Admin.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20240723121224_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Re.Admin.Entity.OrgDept", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code")
                        .HasComment("部门编号");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("CuratorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("curatorId")
                        .HasComment("负责人");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description")
                        .HasComment("描述");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("Layer")
                        .HasColumnType("int")
                        .HasColumnName("layer")
                        .HasComment("层级");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name")
                        .HasComment("部门名称");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id")
                        .HasComment("父ID");

                    b.Property<string>("ParentIds")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("parent_ids")
                        .HasComment("层级IDS");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("phone")
                        .HasComment("电话");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasComment("状态：1正常2停用");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("org_dept", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.OrgDeptEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("DeptId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dept_id")
                        .HasComment("部门ID");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id")
                        .HasComment("员工ID");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_main")
                        .HasComment("是否主职位");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("position_id")
                        .HasComment("职位ID");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("org_dept_employee", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.OrgEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("address")
                        .HasComment("现住址");

                    b.Property<string>("BackIdNoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("back_idno_url")
                        .HasComment("身份证背面");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthday")
                        .HasComment("生日");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code")
                        .HasComment("工号");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("DeptId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dept_id")
                        .HasComment("部门ID");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<string>("FrontIdNoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("front_idno_url")
                        .HasComment("身份证正面");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("idno")
                        .HasComment("身份证");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("in_time")
                        .HasComment("入职时间");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOut")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_out")
                        .HasComment("是否离职");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name")
                        .HasComment("姓名");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("out_time")
                        .HasComment("离职时间");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("phone")
                        .HasComment("手机号码");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("position_id")
                        .HasComment("职位ID");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("Sex")
                        .HasComment("性别");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("关联用户ID");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("org_employee", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.OrgPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code")
                        .HasComment("职位编号");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description")
                        .HasComment("描述");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id")
                        .HasComment("职位分组ID");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level")
                        .HasComment("职级");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name")
                        .HasComment("职位名称");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasComment("状态：1正常2停用");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("org_position", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.OrgPositionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("group_name")
                        .HasComment("职位名");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id")
                        .HasComment("父级ID");

                    b.Property<string>("ParentIds")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("parent_ids")
                        .HasComment("层级父ID");

                    b.Property<string>("Remark")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("remark")
                        .HasComment("备注");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("org_position_group", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysBusinessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("action")
                        .HasComment("操作方法，全名");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address")
                        .HasComment("登录地址");

                    b.Property<string>("Browser")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("browser")
                        .HasComment("浏览器");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("http_method")
                        .HasComment("http请求方式");

                    b.Property<string>("Ip")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ip")
                        .HasComment("IP");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_success")
                        .HasComment("是否成功");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<int>("MillSeconds")
                        .HasColumnType("int")
                        .HasColumnName("mill_seconds")
                        .HasComment("耗时，单位毫秒");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("node_name")
                        .HasComment("操作节点名");

                    b.Property<string>("OperationMsg")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("operation_msg")
                        .HasComment("操作信息");

                    b.Property<string>("Os")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("os")
                        .HasComment("系统");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("url")
                        .HasComment("请求地址");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_name")
                        .HasComment("账号");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_business_log", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysDict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("GroupName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("group_name")
                        .HasComment("组名");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled")
                        .HasComment("是否开启");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key")
                        .HasComment("字典键");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("label")
                        .HasComment("显示文本");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("remark")
                        .HasComment("备注");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序值");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("value")
                        .HasComment("字典值");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_dict", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("ExtraPath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("extra_path")
                        .HasComment("额外地址");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("file_name")
                        .HasComment("文件名");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("mime_type")
                        .HasComment("媒体类型");

                    b.Property<string>("RelativeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("relative_url")
                        .HasComment("后缀");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size")
                        .HasComment("单位KB");

                    b.Property<string>("Suffix")
                        .HasColumnType("longtext")
                        .HasColumnName("suffix")
                        .HasComment("后缀");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("unique_name")
                        .HasComment("文件编号/BLOB名");

                    b.Property<int>("UploadType")
                        .HasColumnType("int")
                        .HasColumnName("upload_type")
                        .HasComment("上传类型 9:BLOB文件系统");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_file", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address")
                        .HasComment("登录地址");

                    b.Property<string>("Browser")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("browser")
                        .HasComment("浏览器");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ip")
                        .HasComment("IP");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_success")
                        .HasComment("是否成功");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("OperationMsg")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("operation_msg")
                        .HasComment("操作信息");

                    b.Property<string>("Os")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("os")
                        .HasComment("系统");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_name")
                        .HasComment("账号");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_login_log", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<int>("FunctionType")
                        .HasColumnType("int")
                        .HasColumnName("function_type")
                        .HasComment("功能类型");

                    b.Property<bool>("Hidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("hidden")
                        .HasComment("是否隐藏");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("icon")
                        .HasComment("图标");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name")
                        .HasComment("组件名");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id")
                        .HasComment("父级ID");

                    b.Property<string>("Path")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("path")
                        .HasComment("路由/地址");

                    b.Property<string>("Permission")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("permission")
                        .HasComment("授权码");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title")
                        .HasComment("显示标题/名称");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_menu", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("remark")
                        .HasComment("备注");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("role_name")
                        .HasComment("角色名");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_role", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysRoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)")
                        .HasColumnName("menu_id")
                        .HasComment("菜单ID");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id")
                        .HasComment("角色ID");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_role_menu", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("avatar")
                        .HasComment("头像");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_time");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleter_id");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_time");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("extra_properties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled")
                        .HasComment("是否启用");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modification_time");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("nickname")
                        .HasComment("昵称");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password")
                        .HasComment("密码");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_salt")
                        .HasComment("密码盐");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("sex")
                        .HasComment("性别");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username")
                        .HasComment("用户名");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_user", (string)null);
                });

            modelBuilder.Entity("Re.Admin.Entity.SysUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id")
                        .HasComment("角色ID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("用户ID");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("sys_user_role", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
